trigger:
  paths:
    include:
      - Dockerfile
      - azure-pipelines.yaml
  branches:
    include:
      - master
      - develop

variables:
  vmImage: "ubuntu-16.04"
  repository: "survivorbat/python3-azure"
  pythonVersion: 3.7

stages:
  - stage: BuildAndPublish
    displayName: Build and publish Image
    jobs:
      - job: BuildAndPublish
        displayName: Build and Publish image
        pool:
          vmImage: $(vmImage)
        steps:
          - task: Docker@2
            displayName: Build
            inputs:
              command: build
              repository: $(repository)
              arguments: --build-arg python_version=$(pythonVersion)
              tags: |
                latest
                $(pythonVersion)
          - task: Docker@2
            displayName: Publish
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
            inputs:
              containerRegistry: 'DockerHub'
              command: push
              repository: $(repository)
              tags: |
                latest
                $(pythonVersion)
